name=Adafruit SSD1306 Enchanced
version=0.1.0
author=catsget
maintainer=catsget
sentence=Enchanced version of Adafruit SSD1306 library
paragraph=Adds additional functional
category=Display
url=https://github.com/adafruit/Adafruit_SSD1306
architectures=*
depends=Adafruit GFX Library, Adafruit SSD1306